apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-jxn2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-jxn2
    app.kubernetes.io/part-of: testing-app
  name: devfile-sample-jxn2
  namespace: christianvogt-tenant
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: devfile-sample-jxn2
    weight: null
status: {}
